name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: cauaosp
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Debug files
        run: ls -R

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
